name: GitHub Actions
run-name: ${{ github.actor }} Testing
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
      - name: setup dependencies pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: run tests
        run: python -m pytest -x test_calc.py

      - name: Deployment
        if: success()
        run: echo "Deployed"