name: GitHub Actions CI/CD
run-name: ${{ github.actor }} Testing
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        run:  python -m pytest -x test_calc.py
      - name: Deployment
        if: success()
        run: echo "Deployed"